const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,DB=path.join(__dirname,'db.json'),ADMIN=(process.env.ADMIN_TOKEN||'dragon-admin-dev-token'),PASS_SECRET=process.env.GAMEPASS_SECRET||'local-verifier';
const dragonArt={ember:'red_dragon.png',verdant:'green_dragon.png',azure:'blue_dragon.png',violet:'purple_dragon.png',solar:'sun_dragon.png',shadow:'shadow_dragon.png',phantom:'phantom_dragon.png',cosmic:'cosmic_dragon.png',gold:'gold_dragon.png'};
const catalog={dragons:[['ember','Ember Whelp','Common',0,0,1,dragonArt.ember],['verdant','Verdant Drake','Uncommon',140,2,2,dragonArt.verdant],['azure','Azure Wyvern','Rare',520,4,4,dragonArt.azure],['violet','Violet Runejaw','Epic',1500,7,8,dragonArt.violet],['solar','Solar Tyrant','Legendary',4200,11,15,dragonArt.solar],['shadow','Shadow Seraph','Mythic',9800,16,28,dragonArt.shadow],['phantom','Phantom Leviathan','Ascendant',22000,22,45,dragonArt.phantom],['cosmic','Cosmic Ancient','Celestial',50000,30,80,dragonArt.cosmic]].map(([id,name,rarity,cost,tier,yieldRate,img])=>({id,name,rarity,cost,tier,yieldRate,img})),eggs:[['cinder','Cinder Egg','Common',25],['moss','Mossbound Egg','Uncommon',90],['storm','Stormglass Egg','Rare',260],['eclipse','Eclipse Egg','Epic',800],['star','Starforged Egg','Legendary',2400]].map(([id,name,rarity,cost])=>({id,name,rarity,cost,img:'egg_icon.png'})),goals:{daily:180,weekly:1250},withdraw:{minimum:20,cooldownMs:86400000,fee:0.06},sinks:[{id:'focus',name:'Forge Focus',cost:300,desc:'+15% next 20 claim reward; expires after use'},{id:'ward',name:'Vault Ward',cost:850,desc:'Marks account for enhanced duplicate-withdrawal protection'},{id:'sigil',name:'Rarity Sigil',cost:1800,desc:'Cosmetic prestige burn; audit logged'}]};
const load=()=>fs.existsSync(DB)?JSON.parse(fs.readFileSync(DB,'utf8')):{users:{},sessions:{},withdrawals:{},audit:[]},save=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));let db=load();
const id=()=>crypto.randomBytes(16).toString('hex'),hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex'),now=()=>Date.now();
function player(uid,email){return db.users[uid] ||= {id:uid,email,admin:false,profile:{name:email.split('@')[0],tier:1,xp:0,created:now(),lastClaim:0,daily:{day:'',earned:0},weekly:{week:'',earned:0}},balances:{aether:60,robux:0},dragons:{ember:{level:1,unlockedAt:now()}},eggs:{cinder:1},withdrawals:[],tx:[],limits:{},flags:{}}}
function session(req){let m=(req.headers.cookie||'').match(/sid=([a-f0-9]+)/);return m&&db.sessions[m[1]]?db.sessions[m[1]]:null}function body(req){return new Promise((res,rej)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6)req.destroy()});req.on('end',()=>{try{res(b?JSON.parse(b):{})}catch(e){rej(e)}})})}
function send(res,code,data,cookie){res.writeHead(code,{'content-type':'application/json',...(cookie?{'set-cookie':cookie}: {})});res.end(JSON.stringify(data))}function bad(res,msg,code=400){send(res,code,{error:msg})}
function tx(u,type,delta,meta={}){u.tx.unshift({id:id(),at:now(),type,delta,meta});u.tx=u.tx.slice(0,80)}function gate(u,key,ms){let t=u.limits[key]||0;if(now()-t<ms)throw Error('rate_limited');u.limits[key]=now()}function day(){return new Date().toISOString().slice(0,10)}function week(){let d=new Date(),onejan=new Date(d.getFullYear(),0,1);return d.getFullYear()+'-W'+Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7)}
function verifyPass(url,amount,email){try{let u=new URL(url),pass=u.searchParams.get('pass')||path.basename(u.pathname),price=Number(u.searchParams.get('price')),sig=u.searchParams.get('sig');let good=hash(`${pass}:${price}:${email}:${PASS_SECRET}`).slice(0,18);return pass&&price===amount&&sig===good}catch{return false}}
async function api(req,res){try{let s=session(req),p=s&&player(s.uid,s.email),b=req.method==='POST'?await body(req):{};if(req.url==='/api/catalog')return send(res,200,{catalog});
if(req.url==='/api/register'||req.url==='/api/login'){let email=String(b.email||'').toLowerCase(),pw=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||pw.length<6)return bad(res,'invalid_credentials');let uid=hash(email).slice(0,24),u=player(uid,email);if(req.url==='/api/register'&&u.password)return bad(res,'account_exists');if(!u.password)u.password=hash(pw);if(u.password!==hash(pw))return bad(res,'wrong_password',401);let sid=id();db.sessions[sid]={uid,email,at:now()};save(db);return send(res,200,{user:safe(u),catalog},`sid=${sid}; HttpOnly; SameSite=Lax; Path=/`)}
if(req.url==='/api/logout'){if(s)Object.keys(db.sessions).forEach(k=>{if(db.sessions[k].uid===s.uid)delete db.sessions[k]});save(db);return send(res,200,{ok:true},'sid=; Max-Age=0; Path=/')}if(!p)return bad(res,'auth_required',401);
if(req.url==='/api/me')return send(res,200,{user:safe(p),catalog});
if(req.url==='/api/claim'){gate(p,'claim',25000);let gain=12+Object.entries(p.dragons).reduce((a,[did,d])=>a+(catalog.dragons.find(x=>x.id===(d.id||did))?.yieldRate||0)*d.level,0);let today=day(),wk=week();if(p.profile.daily.day!==today)p.profile.daily={day:today,earned:0};if(p.profile.weekly.week!==wk)p.profile.weekly={week:wk,earned:0};let cap=160+p.profile.tier*40;if(p.profile.daily.earned+gain>cap)gain=Math.max(0,cap-p.profile.daily.earned);p.balances.aether+=gain;p.profile.xp+=gain;p.profile.tier=Math.max(p.profile.tier,Math.floor(p.profile.xp/500)+1);p.profile.daily.earned+=gain;p.profile.weekly.earned+=gain;tx(p,'Aether claim',gain,{cap});save(db);return send(res,200,{user:safe(p),gain})}
if(req.url==='/api/unlock-dragon'){let d=catalog.dragons.find(x=>x.id===b.id);if(!d)return bad(res,'unknown_dragon');if(p.dragons[d.id])return bad(res,'already_unlocked');if(p.profile.tier<d.tier)return bad(res,'tier_locked');if(p.balances.aether<d.cost)return bad(res,'insufficient_aether');p.balances.aether-=d.cost;p.dragons[d.id]={id:d.id,level:1,unlockedAt:now()};tx(p,'Dragon unlock',-d.cost,{dragon:d.id});save(db);return send(res,200,{user:safe(p)})}
if(req.url==='/api/buy-egg'){let e=catalog.eggs.find(x=>x.id===b.id);if(!e)return bad(res,'unknown_egg');if(p.balances.aether<e.cost)return bad(res,'insufficient_aether');p.balances.aether-=e.cost;p.eggs[e.id]=(p.eggs[e.id]||0)+1;tx(p,'Egg acquisition',-e.cost,{egg:e.id});save(db);return send(res,200,{user:safe(p)})}
if(req.url==='/api/sink'){let sk=catalog.sinks.find(x=>x.id===b.id);if(!sk)return bad(res,'unknown_sink');if(p.balances.aether<sk.cost)return bad(res,'insufficient_aether');p.balances.aether-=sk.cost;p.flags[sk.id]=(p.flags[sk.id]||0)+1;tx(p,'Economy sink',-sk.cost,{sink:sk.id});save(db);return send(res,200,{user:safe(p)})}
if(req.url==='/api/withdraw'){gate(p,'withdraw_try',10000);let amount=Math.floor(Number(b.amount));if(amount<catalog.withdraw.minimum)return bad(res,'minimum_20_robux');if(p.balances.robux<amount)return bad(res,'insufficient_robux');let recent=Object.values(db.withdrawals).find(w=>w.uid===p.id&&['pending','approved'].includes(w.state)&&now()-w.at<catalog.withdraw.cooldownMs);if(recent)return bad(res,'cooldown_or_duplicate');if(!verifyPass(String(b.gamepassUrl||''),amount,p.email))return bad(res,'gamepass_validation_failed');let wid=id();db.withdrawals[wid]={id:wid,uid:p.id,email:p.email,amount,gamepassUrl:b.gamepassUrl,state:'pending',at:now(),reviewedAt:null};p.balances.robux-=amount;p.withdrawals.unshift(wid);tx(p,'Withdrawal pending',-amount,{wid});save(db);return send(res,200,{user:safe(p),withdrawal:db.withdrawals[wid]})}
if(req.url.startsWith('/api/admin')){if(!p.admin&&req.headers['x-admin-token']!==ADMIN)return bad(res,'admin_forbidden',403);if(req.url==='/api/admin')return send(res,200,{users:Object.values(db.users).map(safe),withdrawals:Object.values(db.withdrawals),audit:db.audit.slice(-60)});if(req.url==='/api/admin/review'){let w=db.withdrawals[b.id],u=w&&db.users[w.uid];if(!w||!u||w.state!=='pending')return bad(res,'invalid_request');w.state=b.approve?'approved':'rejected';w.reason=String(b.reason||'');w.reviewedAt=now();if(!b.approve){u.balances.robux+=w.amount;tx(u,'Withdrawal rejected refund',w.amount,{wid:w.id})}db.audit.push({at:now(),admin:p.email,action:'withdraw_review',wid:w.id,state:w.state});save(db);return send(res,200,{ok:true})}if(req.url==='/api/admin/grant'){let u=db.users[b.uid],amt=Math.floor(Number(b.amount));if(!u||!Number.isFinite(amt)||Math.abs(amt)>100000)return bad(res,'invalid_grant');u.balances.aether+=amt;tx(u,'Admin aether grant',amt,{by:p.email});db.audit.push({at:now(),admin:p.email,action:'grant',uid:b.uid,amt});save(db);return send(res,200,{user:safe(u)})}}
bad(res,'not_found',404)}catch(e){bad(res,e.message||'server_error',e.message==='rate_limited'?429:500)}}
function safe(u){return {id:u.id,email:u.email,admin:u.admin,profile:u.profile,balances:u.balances,dragons:u.dragons,eggs:u.eggs,withdrawals:u.withdrawals.map(id=>db.withdrawals[id]).filter(Boolean),tx:u.tx,flags:u.flags}}
http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let file=req.url==='/'?'index.html':req.url.split('?')[0].slice(1),p=path.join(__dirname,file);if(!p.startsWith(__dirname)||!fs.existsSync(p))p=path.join(__dirname,'index.html');res.end(fs.readFileSync(p))}).listen(PORT,()=>console.log('DRAGONBLOX listening on http://localhost:'+PORT));
